apiVersion: apps/V1
kinds: Deployment
metadata:
  name: deploy1
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: label1
  template:
    metadata:
      labels:
        app: label1
    spec:
      container:
      - name:
        image:
        port:
        - containerPort: 80